language: node_js
sudo: required
node_js: 7

install:
  - curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh
  - npm install -g meteor-build-client

script:
  - cd app && meteor-build-client ../build --path "/"

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
