language: node_js
node_js: 7

script:
  npm install -g meteor-build-client
  cd app && meteor-build-client ../build --path "/"

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
